In [2]:
from sklearn.neighbors import KNeighborsClassifier
#from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
#data = np.loadtxt("/content/drive/MyDrive/Concept of Technologies and AI/zoo_data-1.csv",delimiter=",",skiprows=1)
import numpy as np

# Load the CSV file into a NumPy array
array = np.genfromtxt("/content/drive/MyDrive/Concept of Technologies and AI/zoo_data-1.csv", delimiter=",", skip_header=1, dtype=float)

# Print the resulting array
# print(array)

X=array[:,1:-1]
#Every data excluding catsize which is our predicting data
print(X)

#This is our predicting data: catsize
y=array[:,-1]
# print(y)

[[1. 0. 0. ... 4. 0. 0.]
 [1. 0. 0. ... 4. 1. 0.]
 [0. 0. 1. ... 0. 1. 0.]
 ...
 [1. 0. 0. ... 4. 1. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 2. 1. 0.]]


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)




In [ ]:
clf = KNeighborsClassifier(n_neighbors=7)


In [ ]:
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [ ]:
print("Predictions for the first 5 samples:", clf.predict(X_test[:5]))

Predictions for the first 5 samples: [1. 1. 1. 1. 1.]


In [ ]:
print("Class probabilities for the first 5 samples:", clf.predict_proba(X_test[:5]))

Class probabilities for the first 5 samples: [[0.42857143 0.57142857]
 [0.28571429 0.71428571]
 [0.42857143 0.57142857]
 [0.28571429 0.71428571]
 [0.28571429 0.71428571]]


In [ ]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy of the model:", accuracy)

Accuracy of the model: 0.9032258064516129


In [ ]:
accuracy_alternative = clf.score(X_test, y_test)
print("Accuracy of the model (using score method):", accuracy_alternative)

Accuracy of the model (using score method): 0.9032258064516129


In [1]:
 # Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=42)
# Set hyper-parameters for the KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=5)
clf.fit(X_train, y_train)
predictions = clf.predict(X_test)
print(predictions)
# Compute class probabilities for the test data
probabilities = clf.predict_proba(X_test)
#print("Class probabilities for the test data:",probabilities)

NameError: name 'train_test_split' is not defined

### Implementation of Linear Regression

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [3]:
df = pd.read_csv("/content/drive/MyDrive/Concept of Technologies and AI/zoo_data-1.csv")
df.head()

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  
0        1         1         1         0     0     4     0         0        1  
1        1         1         1         0     0     4     1         0        1  
2        1         1         0         0     1     0     1         0        0  
3        1         1         1         0     0     4     0         0        1  
4        1         1         1         0     0     4     1         0        1

In [13]:
X = df.drop(['animal_name', 'catsize'], axis=1)
y = df['catsize']

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
model = LinearRegression()
model.fit(X_train, y_train)



LinearRegression()

In [18]:
y_pred = model.predict(X_test)



In [ ]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")


### Implementation of Logistic Regression

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd

In [20]:
df = pd.read_csv('/content/drive/MyDrive/Concept of Technologies and AI/medical_students_dataset.csv')
df.head()

Student ID   Age  Gender      Height     Weight Blood Type        BMI  \
0         1.0  18.0  Female  161.777924  72.354947          O  27.645835   
1         2.0   NaN    Male  152.069157  47.630941          B        NaN   
2         3.0  32.0  Female  182.537664  55.741083          A  16.729017   
3         NaN  30.0    Male  182.112867  63.332207          B  19.096042   
4         5.0  23.0  Female         NaN  46.234173          O        NaN   

   Temperature  Heart Rate  Blood Pressure  Cholesterol Diabetes Smoking  
0          NaN        95.0           109.0        203.0       No     NaN  
1    98.714977        93.0           104.0        163.0       No      No  
2    98.260293        76.0           130.0        216.0      Yes      No  
3    98.839605        99.0           112.0        141.0       No     Yes  
4    98.480008        95.0             NaN        231.0       No      No

In [39]:
X = df.drop(['Gender','Diabetes','Smoking','Blood Type'], axis=1)
y = df['Diabetes']
X.head()

Student ID   Age      Height     Weight        BMI  Temperature  \
0         1.0  18.0  161.777924  72.354947  27.645835          NaN   
1         2.0   NaN  152.069157  47.630941        NaN    98.714977   
2         3.0  32.0  182.537664  55.741083  16.729017    98.260293   
3         NaN  30.0  182.112867  63.332207  19.096042    98.839605   
4         5.0  23.0         NaN  46.234173        NaN    98.480008   

   Heart Rate  Blood Pressure  Cholesterol  
0        95.0           109.0        203.0  
1        93.0           104.0        163.0  
2        76.0           130.0        216.0  
3        99.0           112.0        141.0  
4        95.0             NaN        231.0

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [50]:
model = LogisticRegression(max_iter=50) # Increased max_iter to ensure convergence
X_train = X_train.fillna(0)
y_train = y_train.fillna(0)
model.fit(X_train, y_train)

TypeError: '<' not supported between instances of 'int' and 'str'

In [ ]:

y_pred = model.predict(X_test)



In [ ]:

accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)



In [ ]:
print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{class_report}")