In [14]:
import numpy as np
#  Problem- 1: Array Creation:
#  Complete the following Tasks:
#  1. Initialize an empty array with size 2X2.
#  2. Initialize an all one array with size 4X2.
#  3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
#  4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
#  5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
#  6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
empty_array=np.empty((2,2))
ones_array = np.ones((4, 2))
filled_array = np.full((2,2), fill_value=4)
zeros_like_array = np.zeros_like([[1, 2, 3], [4, 5, 6]])
ones_like_array = np.ones_like([[1, 2, 3], [4, 5, 6]])
converted_array = np.array([1, 2, 3, 4])
empty_array,ones_array,filled_array,zeros_like_array,ones_like_array,converted_array

(array([[6.37401647e-067, 2.16847421e-028],
        [1.08662730e-312, 0.00000000e+000]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[4, 4],
        [4, 4]]),
 array([[0, 0, 0],
        [0, 0, 0]]),
 array([[1, 1, 1],
        [1, 1, 1]]),
 array([1, 2, 3, 4]))

In [30]:
 # 4.1.1 Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:
 # Complete the following tasks:
 # 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
 # 2. Create a 3X3 matrix with values ranging from 0 to 8.
 # {Hint:look for np.reshape()}
 # 3. Create a 3X3 identity matrix.{Hint:np.eye()}
 # 4. Create a random array of size 30 and find the mean of the array.
 # {Hint:check for np.random.random() and array.mean() function}
 # 5. Create a 10X10 array with random values and find the minimum and maximum values.
 # 6. Create a zero array of size 10 and replace 5th element with 1.
 # 7. Reverse an array arr = [1,2,0,0,4,0].
 # 8. Create a 2d array with 1 on border and 0 inside.
 # 9. Create a 8X8 matrix and fill it with a checkerboard pattern.
import numpy as np

# 1. Create an array with values ranging from 10 to 49.
array_range = np.arange(10, 50)
print("1. Array with values ranging from 10 to 49:")
print(array_range)

# 2. Create a 3X3 matrix with values ranging from 0 to 8.
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 Matrix with values ranging from 0 to 8:")
print(matrix_3x3)

# 3. Create a 3X3 identity matrix.
identity_matrix = np.eye(3)
print("\n3. 3x3 Identity matrix:")
print(identity_matrix)

# 4. Create a random array of size 30 and find the mean of the array.
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\n4. Random array of size 30 and its mean:")
print(random_array)
print("Mean:", mean_value)

# 5. Create a 10X10 array with random values and find the minimum and maximum values.
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n5. 10x10 Array with random values, minimum, and maximum values:")
print(random_10x10)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

# 6. Create a zero array of size 10 and replace 5th element with 1.
zero_array = np.zeros(10)
zero_array[4] = 1
print("\n6. Zero array of size 10 with 5th element replaced with 1:")
print(zero_array)

# 7. Reverse an array arr = [1,2,0,0,4,0].
arr = [1, 2, 0, 0, 4, 0]
reversed_arr = np.array(arr)[::-1]
print("\n7. Reversed array:")
print(reversed_arr)

# 8. Create a 2D array with 1 on border and 0 inside.
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n8. 2D array with 1 on border and 0 inside:")
print(border_array)

# 9. Create an 8X8 matrix and fill it with a checkerboard pattern.
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. 8x8 Checkerboard pattern:")
print(checkerboard)


1. Array with values ranging from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 Matrix with values ranging from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array of size 30 and its mean:
[0.97152149 0.20528747 0.19903213 0.53247068 0.04890226 0.13659867
 0.49414969 0.05637977 0.08060299 0.4779028  0.30041472 0.33117747
 0.99561769 0.52248704 0.6344972  0.96003986 0.94108364 0.77868679
 0.56734586 0.85231613 0.28532285 0.434627   0.68995682 0.35314722
 0.45293086 0.54156339 0.22911608 0.3508573  0.03974394 0.14764061]
Mean: 0.45371401403013956

5. 10x10 Array with random values, minimum, and maximum values:
[[0.9149619  0.70046646 0.3795541  0.51854054 0.97364524 0.09620229
  0.39877286 0.07162649 0.99100189 0.6878339 ]
 [0.33651558 0.28758613 0.40161204 0.7879332  0.77517659 0.47814735
  0.4632587  0.58014027 0.99870443 0.504154

In [32]:
import numpy as np

# Define the given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays.
add_arrays = x + y
print("1. Addition of x and y:")
print(add_arrays)

# 2. Subtract the two arrays.
subtract_arrays = x - y
print("\n2. Subtraction of x and y:")
print(subtract_arrays)

# 3. Multiply the array with any integer of your choice (e.g., 3).
multiply_array = x * 3
print("\n3. Multiplication of x with 3:")
print(multiply_array)

# 4. Find the square of each element of the array.
square_array = x ** 2
print("\n4. Square of each element in x:")
print(square_array)

# 5. Find the dot product:
dot_product_vw = np.dot(v, w)  # v and w
dot_product_xv = np.dot(x, v)  # x and v
dot_product_xy = np.dot(x, y)  # x and y
print("\n5. Dot products:")
print("Dot product of v and w:", dot_product_vw)
print("Dot product of x and v:")
print(dot_product_xv)
print("Dot product of x and y:")
print(dot_product_xy)

# 6. Concatenate x and y along row, and v and w along column.
concatenate_xy_row = np.concatenate((x, y), axis=0)  # Along rows
concatenate_vw_col = np.vstack((v, w))  # Along columns
print("\n6. Concatenation:")
print("Concatenate x and y along rows:")
print(concatenate_xy_row)
print("Concatenate v and w along columns:")
print(concatenate_vw_col)

# 7. Concatenate x and v; if there's an error, explain why.
try:
    concatenate_xv = np.concatenate((x, v), axis=0)  # Attempt to concatenate
    print("\n7. Concatenate x and v:")
    print(concatenate_xv)
except ValueError as e:
    print("\n7. Error when concatenating x and v:")
    print(e)
    print("Explanation: The shapes of x and v are incompatible for concatenation along axis=0. "
          "x has shape (2, 2) while v has shape (2,). To fix, you could reshape v to have the same dimensions as x.")


1. Addition of x and y:
[[ 6  8]
 [10 13]]

2. Subtraction of x and y:
[[-4 -4]
 [-4 -3]]

3. Multiplication of x with 3:
[[ 3  6]
 [ 9 15]]

4. Square of each element in x:
[[ 1  4]
 [ 9 25]]

5. Dot products:
Dot product of v and w: 219
Dot product of x and v:
[29 77]
Dot product of x and y:
[[19 22]
 [50 58]]

6. Concatenation:
Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
[[ 9 10]
 [11 12]]

7. Error when concatenating x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: The shapes of x and v are incompatible for concatenation along axis=0. x has shape (2, 2) while v has shape (2,). To fix, you could reshape v to have the same dimensions as x.


In [34]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
# Compute the inverse of A
A_inv = np.linalg.inv(A)

# Compute A * A^-1
result = np.dot(A, A_inv)

# Verify if the result is an identity matrix
identity_matrix = np.eye(2)  # Identity matrix of size 2x2
print("1. A * A^-1:")
print(result)
print("Is A * A^-1 equal to the identity matrix?", np.allclose(result, identity_matrix))

# Compute AB and BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("\n2. AB and BA:")
print("AB:")
print(AB)
print("BA:")
print(BA)
print("Is AB equal to BA?", np.allclose(AB, BA))  # This should return False

# Compute (AB)^T and B^T * A^T
AB_transpose = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))

print("\n3. (AB)^T and B^T * A^T:")
print("(AB)^T:")
print(AB_transpose)
print("B^T * A^T:")
print(BT_AT)
print("Is (AB)^T equal to B^T * A^T?", np.allclose(AB_transpose, BT_AT))

# Define matrix A and vector B
coeff_matrix = np.array([[2, -3, 1],
                         [1, -1, 2],
                         [3,  1, -1]])
constants = np.array([-1, -3, 9])

# Solve for X using np.linalg.inv
A_inv = np.linalg.inv(coeff_matrix)
solution = np.dot(A_inv, constants)

print("\n4. Solution to the system of equations using inverse method:")
print("Solution (x, y, z):", solution)


# Solve for X directly using np.linalg.solve
solution_direct = np.linalg.solve(coeff_matrix, constants)

print("\n5. Solution to the system of equations using np.linalg.solve:")
print("Solution (x, y, z):", solution_direct)


1. A * A^-1:
[[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]
Is A * A^-1 equal to the identity matrix? True

2. AB and BA:
AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]
Is AB equal to BA? False

3. (AB)^T and B^T * A^T:
(AB)^T:
[[23 51]
 [13 29]]
B^T * A^T:
[[23 51]
 [13 29]]
Is (AB)^T equal to B^T * A^T? True

4. Solution to the system of equations using inverse method:
Solution (x, y, z): [ 2.  1. -2.]

5. Solution to the system of equations using np.linalg.solve:
Solution (x, y, z): [ 2.  1. -2.]
